version: '3.4'
services:
    script:
        build:
            context: .
        depends_on:
            - meilisearch
    meilisearch:
        image: getmeili/meilisearch
        command: ./meilisearch 
        ports:
            -   target: 7700
                published: 7700
                protocol: tcp